baseURL = "https://camel.apache.org/"
languageCode = "en-us"
title = "Apache Camel"
relativeURLs = true
disablePathToLower = true
staticDir = ["static", "documentation"]
disableKinds = ["taxonomyTerm"]
enableRobotsTXT = true
timeout = 300000

[markup]
defaultMarkdownHandler = "blackfriday"
    [markup.blackfriday]
        nofollowLinks = true
        noreferrerLinks = true

[params]
    socialProfiles = ["https://twitter.com/RedHat"]
    organizationLogo = "https://openshift-integration.github.io/kamelet-catalog/camel-kamelets/_/img/logo-redhat.svg"
    organizationDescription = "Red Hat is the world’s enterprise open source leader"
    GitHubAPI = "https://api.github.com"

[caches]

    [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "12h"

    [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "12h"

[sitemap]
  filename = "sitemap-website.xml"

[[menu.main]]
    name = "Kamelet Catalog"
    weight = 2
    identifier = "kamelet-catalog"
    url = "/"
    pre = "/_/img/documentation.svg"

[permalinks]
    blog = "blog/:year/:month/:filename/"

[privacy]

  [privacy.youtube]
    privacyEnhanced = true
